config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  post_id    :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  validates :content, :post_id, :author_id, presence: true

  belongs_to :post

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(
                     content: comment_params[:content],
                     post_id: comment_params[:post_id],
                     author_id: current_user.id)
    if @comment.save
      redirect_to post_url(comment_params[:post_id])
    else
      flash.now[:errors] = [@comment.errors.full_messages]
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

  def user_check
    unless current_user
      flash[:errors] = ["Only logged in users can make posts"]
      redirect_to subs_url
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<form  action=" <%= comment_url(@comment) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label>Content:
    <input type="text" name="comment[content]" value="<%= @comment.content %>">
  </label>

  <input type="submit" value="Edit Comment">
</form>

app/views/comments/new.html.erb
<form  action=" <%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
  <label>Content:
    <input type="text" name="comment[content]" value="<%= @comment.content %>">
  </label>


  <input type="submit" value="Post Comment">
</form>