config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :posts,
    through: :post_subs,
    source: :post

  has_many :post_subs

  validates :moderator_id, :title, :description, presence: true
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :moderator_check, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    user = User.find_by(user_name: params[:sub][:moderator])
    if user
      moderator_id = user.id
    end

    if @sub.update(title: sub_params[:title], description: sub_params[:description], moderator_id: @sub.moderator_id)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = [@sub.errors.full_messages]
      render :edit
    end
  end

  def create
    user = User.find_by(user_name: params[:sub][:moderator])
    if user
      moderator_id = user.id
    end

    @sub = Sub.new(title: sub_params[:title], description: sub_params[:description], moderator_id: moderator_id)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = [@sub.errors.full_messages]
      render :new
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    if @sub
      render :show
    else
      flash[:errors] = ["No sub found"]
      redirect_to subs_url
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

  def moderator_check
    @sub = Sub.find_by(id: params[:id])
    unless current_user && current_user.id == @sub.moderator_id
      flash[:errors] = ["Only moderators can edit subs"]
      redirect_to sub_url(@sub)
    end
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
<form  action=" <%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <%= auth_token %>
  <label>Title:
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description:
    <textarea name="sub[description]" rows="8" cols="40" placeholder="Enter description"><%= @sub.description  %>></textarea>
  </label>

  <input type="submit" value="Update Sub">
</form>

app/views/subs/index.html.erb
<ul>
  <% @subs.each do |sub| %>
    <li>
    <%= link_to "#{sub.title}", sub_url(sub), method: :get %>
    </li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<form  action=" <%= subs_url %>" method="post">
  <%= auth_token %>
  <label>Title:
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Moderator:
    <input type="text" name="sub[moderator]" value="<%= @sub.moderator %>">
  </label>

  <label>Description:
    <textarea name="sub[description]" rows="8" cols="40" placeholder="Enter description"><%= @sub.description %></textarea>
  </label>

  <input type="submit" value="Create Sub">
</form>

app/views/subs/show.html.erb
<h1> <%= @sub.title %></h1>
<h2> <%= @sub.description %></h2>
<p> <%= @sub.moderator.user_name %> </p>
<%= link_to "edit sub", edit_sub_url, method: :get %>
<%= button_to "Write new post", new_post_url, method: :get %>

<ul>
  <% @sub.posts.each do |post| %>
    <li><%= link_to "#{post.title}", post_url(post), method: :get %></li>
  <% end %>
</ul>