config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :text
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :content, :url, :author_id,  presence: true
  validate :has_a_sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments

  private
  def has_a_sub
    unless self.subs.size > 0
      self.errors[:you] << "must select more than one sub."
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :author_check, only: [:edit, :update, :delete]
  before_action :user_check, only: [:new, :create]

  def destroy
    @post = Post.find(params[:id])
    sub_id = @post.sub_id
    @post.destroy
    redirect_to sub_url(sub_id)
  end

  def new
    @post = Post.new
    render :new
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(title: post_params[:title],
                     content: post_params[:content],
                     url: post_params[:url],
                     sub_ids: post_params[:sub_ids],
                     author_id: current_user.id)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = [@post.errors.full_messages]
      render :new
    end

  end

  def create
    @post = Post.new(title: post_params[:title],
                     content: post_params[:content],
                     url: post_params[:url],
                     author_id: current_user.id)
    @post.sub_ids = post_params[:sub_ids]
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = [@post.errors.full_messages]
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    if @post
      render :show
    else
      flash[:errors] = ["No post found"]
      redirect_to subs_url
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :url, :sub_title, sub_ids: [])
  end

  def author_check
    @post = Post.find_by(id: params[:id])
    unless current_user && current_user.id == @post.author_id
      flash[:errors] = ["Only this post's author can make edits"]
      redirect_to post_url(@post)
    end
  end

  def user_check
    unless current_user
      flash[:errors] = ["Only logged in users can make posts"]
      redirect_to subs_url
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<form  action=" <%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label>Title:
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL:
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%= sub.id %>"
             <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    </label>
  <% end %>


  <label>Content:
    <textarea name="post[content]" rows="8" cols="40" placeholder="Enter content"><%= @post.content %></textarea>
  </label>

  <input type="submit" value="Edit Post">
</form>

app/views/posts/new.html.erb
<form  action=" <%= posts_url %>" method="post">
  <%= auth_token %>
  <label>Title:
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL:
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%= sub.id %>"
             <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    </label>
  <% end %>

  <label>Content:
    <textarea name="post[content]" rows="8" cols="40" placeholder="Enter content"><%= @post.content %></textarea>
  </label>

  <input type="submit" value="Create Post">
</form>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<h1> <%= @post.content %> </h1>
<%= link_to "#{@post.url}", @post.url, method: :get %>

<ul>
<% @post.comments.each do |comment| %>
<li>
  User:
  <%= comment.author.user_name %>
  Content:
  <%= comment.content %>
</li>
<% end %>
</ul>

<%= button_to "Post new Comment", new_post_comment_url(@post.id), method: :get %>
<%= button_to "Edit Post", edit_post_url, method: :get %>
<%= button_to "Delete Post", post_url(@post), method: :delete %>
Go back to:

<% @post.subs.each do |sub| %>
  <%= link_to "#{sub.title}", sub_url(sub), method: :get %>
<% end %>